# CMake generated Testfile for 
# Source directory: /home/voskan/Desktop/Apex-X/runtime/tensorrt
# Build directory: /home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[trt_tilepack_plugin_native]=] "/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15/apexx_trt_tilepack_test")
set_tests_properties([=[trt_tilepack_plugin_native]=] PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15:/home/voskan/Desktop/Apex-X/artifacts/toolchains/tensorrt_10_15_1_29/lib:/home/voskan/anaconda3/lib/python3.13/site-packages/tensorrt_libs:/home/voskan/anaconda3/targets/x86_64-linux/lib:" _BACKTRACE_TRIPLES "/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;222;add_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;273;apexx_register_trt_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;0;")
add_test([=[trt_tileunpackfusion_plugin_native]=] "/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15/apexx_trt_tileunpackfusion_test")
set_tests_properties([=[trt_tileunpackfusion_plugin_native]=] PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15:/home/voskan/Desktop/Apex-X/artifacts/toolchains/tensorrt_10_15_1_29/lib:/home/voskan/anaconda3/lib/python3.13/site-packages/tensorrt_libs:/home/voskan/anaconda3/targets/x86_64-linux/lib:" _BACKTRACE_TRIPLES "/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;222;add_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;300;apexx_register_trt_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;0;")
add_test([=[trt_tilessm_plugin_native]=] "/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15/apexx_trt_tilessm_test")
set_tests_properties([=[trt_tilessm_plugin_native]=] PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15:/home/voskan/Desktop/Apex-X/artifacts/toolchains/tensorrt_10_15_1_29/lib:/home/voskan/anaconda3/lib/python3.13/site-packages/tensorrt_libs:/home/voskan/anaconda3/targets/x86_64-linux/lib:" _BACKTRACE_TRIPLES "/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;222;add_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;327;apexx_register_trt_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;0;")
add_test([=[trt_nms_decode_plugin_native]=] "/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15/apexx_trt_nms_decode_test")
set_tests_properties([=[trt_nms_decode_plugin_native]=] PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/voskan/Desktop/Apex-X/runtime/tensorrt/build_cuda_10_15:/home/voskan/Desktop/Apex-X/artifacts/toolchains/tensorrt_10_15_1_29/lib:/home/voskan/anaconda3/lib/python3.13/site-packages/tensorrt_libs:/home/voskan/anaconda3/targets/x86_64-linux/lib:" _BACKTRACE_TRIPLES "/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;222;add_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;354;apexx_register_trt_test;/home/voskan/Desktop/Apex-X/runtime/tensorrt/CMakeLists.txt;0;")
