from .aggregation import (
    PVTileAggregation,
    aggregate_pv_maps_to_ff_tile_vectors,
    compute_ff_tile_bounds_on_pv_grid,
)
from .core import (
    GreedyBudgetController,
    IdentityRouter,
    TemporalStabilityMetrics,
    count_mask_toggles,
    delta_loss_oracle,
    dual_update,
    expected_cost,
    greedy_utility_per_cost,
    hysteresis_rollout,
    hysteresis_update,
    hysteresis_update_with_budget,
    mean,
    mean_active_ratio,
    sigmoid,
    split_by_budget,
    stable_rank_tile_ids,
    ste_gate,
    summarize_temporal_stability,
    temporal_consistency,
    tile_flip_rate,
)
from .cost_model import CalibrationRecord, LevelCost, StaticCostModel
from .diagnostics import build_routing_diagnostics, utility_histogram
from .dual_budget import BudgetDualController
from .gating import GateMode, sigmoid_probabilities, ste_gate_from_utilities, ste_hard_gate
from .inference_budget import (
    GreedySelectionResult,
    ThreeStageSelectionResult,
    TwoStageSelectionResult,
    build_kmax_buffer,
    deterministic_greedy_selection,
    deterministic_three_stage_selection,
    deterministic_two_stage_selection,
)
from .interfaces import (
    BudgetController,
    BudgetControllerProtocol,
    CostModel,
    CostModelProtocol,
    Router,
    RouterProtocol,
)
from .kan_like import LightweightSplineActivation, RouterKANLike, RouterKANOutput
from .oracle_distill import (
    OracleDeltaStats,
    OracleDeltaTargets,
    RegressionLossType,
    UtilityOracleLossOutput,
    compute_oracle_delta_targets,
    summarize_oracle_delta_targets,
    utility_oracle_loss,
    utility_ranking_loss,
    utility_regression_loss,
)
from .oracle_sampling import OracleSetSample, sample_oracle_set
from .tiny_mlp import RouterTinyMLP, RouterTinyOutput

__all__ = [
    "BudgetController",
    "BudgetControllerProtocol",
    "CostModel",
    "CostModelProtocol",
    "Router",
    "RouterProtocol",
    "LightweightSplineActivation",
    "RouterKANOutput",
    "RouterKANLike",
    "PVTileAggregation",
    "compute_ff_tile_bounds_on_pv_grid",
    "aggregate_pv_maps_to_ff_tile_vectors",
    "OracleSetSample",
    "sample_oracle_set",
    "RegressionLossType",
    "OracleDeltaStats",
    "OracleDeltaTargets",
    "UtilityOracleLossOutput",
    "compute_oracle_delta_targets",
    "utility_regression_loss",
    "utility_ranking_loss",
    "utility_oracle_loss",
    "summarize_oracle_delta_targets",
    "RouterTinyOutput",
    "RouterTinyMLP",
    "LevelCost",
    "CalibrationRecord",
    "StaticCostModel",
    "IdentityRouter",
    "GreedyBudgetController",
    "BudgetDualController",
    "utility_histogram",
    "build_routing_diagnostics",
    "sigmoid",
    "ste_gate",
    "delta_loss_oracle",
    "expected_cost",
    "dual_update",
    "GateMode",
    "sigmoid_probabilities",
    "ste_hard_gate",
    "ste_gate_from_utilities",
    "GreedySelectionResult",
    "TwoStageSelectionResult",
    "ThreeStageSelectionResult",
    "build_kmax_buffer",
    "deterministic_greedy_selection",
    "deterministic_two_stage_selection",
    "deterministic_three_stage_selection",
    "greedy_utility_per_cost",
    "stable_rank_tile_ids",
    "hysteresis_update",
    "hysteresis_update_with_budget",
    "hysteresis_rollout",
    "count_mask_toggles",
    "tile_flip_rate",
    "temporal_consistency",
    "mean_active_ratio",
    "TemporalStabilityMetrics",
    "summarize_temporal_stability",
    "split_by_budget",
    "mean",
]
